issue #191 : google tts plugin is broken
NaomiProject/Naomi pull request #198
Opened 2019-07-04 21:15 UTC by olest

The google api for TTS has changed and the current plugin is not longer working.

## Description
I have updated the plugin to the new google TTS api.

## Motivation and Context
As explained above, it changes the plugin to use the new api.

## How Has This Been Tested?
I don't know how to write tests for a tts plugin but I tried it using my google account and it works.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2019-07-04 21:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NaomiProject/Naomi?pullRequest=198) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/NaomiProject/Naomi?pullRequest=198) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: aaronchantrill<br/>:x: olest<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NaomiProject/Naomi?pullRequest=198) it.</sub>

2019-07-05 15:52 UTC, aaronchantrill requested changes
First, of all, good job! You got text to speech working with the new Google Cloud!

Here is my experience so far.
First, due to an unrelated issue, I was unable to get the populate program to accept Google as my TTS engine. This was because there is a new variable which indicates that a voice has been chosen which never got set for the "Google" TTS choice. More on this later. We are currently in the process of transitioning away from populate.py to the "settings" system, so things are a bit mucked up at the moment.

After fixing populate.py to accept Google as a TTS engine, I got the following error:
```
WARNING:naomi.pluginstore:Plugin at '/home/pi/Naomi_GoogleTTS/plugins/tts/google-tts' skipped! (Reason: cannot import name 'texttospeech')
Traceback (most recent call last):
  File "/home/pi/Naomi_GoogleTTS/plugins/tts/google-tts/google.py", line 7, in <module>
    from google.cloud import texttospeech
ImportError: cannot import name 'texttospeech' 
```
To fix this error, I had to run the following command:
`pip3 install google-cloud-texttospeech`
without this, the plugin would not load, so never asked me the location of my credentials file.

After installing the texttospeech library, it did ask me the location of the credentials file which I entered. Then I got this message:
```
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials.
Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run
the application. For more information, please see
https://cloud.google.com/docs/authentication/getting-started
```
I realized that although it is asking for a credentials file, it was not actually using the credentials file. I added the code in used for pulling the authentication information from the profile last time, and also changed the name of the setting to match what we ended up with in the Google STT engine (google: credentials_json:).

Now that the credentials were entered and set up, I got the following error message:
```
google.api_core.exceptions.PermissionDenied: 403 Cloud Text-to-Speech API has not been
used in project {project id} before or it is disabled. Enable it by visiting
https://console.developers.google.com/apis/api/texttospeech.googleapis.com/overview?project={project id} 
then retry. If you enabled this API recently, wait a few minutes for the action 
to propagate to our systems and retry.
```
Following the link in the message and signing into Google took me to the "Enable the Google Cloud Text to Speech" API button, so that was great. After clicking the button and waiting about 5 minutes, the Google TTS plugin started working.

While reading the documentation, I did find that there are a variety of different voices for different language choices. I started a python3 interactive session and entered the following lines:
```
>>> from google.cloud import texttospeech
>>> from google.oauth2 import service_account
>>> credentials_json = "/home/pi/.naomi/google_auth.json"
>>> cred = service_account.Credentials.from_service_account_file(credentials_json)
>>> client = texttospeech.TextToSpeechClient(credentials=cred)
>>> voices = client.list_voices()
>>> for voice in voices.voices:
...     if "en-US" in voice.language_codes:
...         print(voice)
... 
language_codes: "en-US"
name: "en-US-Wavenet-A"
ssml_gender: MALE
natural_sample_rate_hertz: 24000
...bunch more voices here...
language_codes: "en-US"
name: "en-US-Standard-E"
ssml_gender: FEMALE
natural_sample_rate_hertz: 24000
```
It would be nice to give the user a list of voices based on their selected language preference, then let them select and preview the voice they want to use.

At the same time, it would probably be good to let them know that the "WaveNet" voices are currently quite a bit more expensive than the "Standard" voices. From https://cloud.google.com/text-to-speech/pricing:

|Feature | Monthly free tier | Paid usage|
|--- | --- | ---|
|Standard (non-WaveNet) voices | 0 to 4 million characters | $4.00 USD / 1 million characters|
|WaveNet voices | 0 to 1 million characters | $16.00 USD / 1 million characters|

It's unlikely that a home user or developer would run up against those limits in a month, but it's good to keep in mind.

I am working on installation scripts for 3rd party developer plugins right now, including an install.py program that is run when the plugin is installed, updated, or first run, which might be a good way to ensure that the necessary python requirements get installed, and provide some additional information to the user during setup.

So, for now there are just a couple of changes that I had to make to get this working on my system. I'll do a pull request against your repository with those changes.

Thanks!

2019-07-05 20:43 UTC, olest commented
Hi, thanks for the thorough review and sorry that it did not work immediately. Yes, I please do send a pull request.

2019-07-05 22:07 UTC, aaronchantrill approved these changes
Okay, looks good to me. I'm going to merge it.

2019-07-05 22:15 UTC, merged