Added Issue: #124 - Adding lists for keywords
NaomiProject/Naomi pull request #217
Opened 2019-10-12 13:50 UTC by jeliebig

Hello,
I added the requested feature in #124 mainly by changing how simple_input responds to lists. You are still able to use strings as a keyword but from naomi's side it will be treated as a list now. This also had to change the profile.yaml so that keywords could be configured as lists. Even if you use just one string you can still do it as long as you stick to the config file behavior.

## Related Issue
Issue: #124 

## Motivation and Context
Now people are able to use more than one keyword without any heavy changes in their config files.

## How Has This Been Tested?
I set up a Ubuntu VM and installed a fresh naomi-dev on it. I tried to change my config file and used the debug flag of Naomi.py to see if everything works well. I also created new profiles to see if anything keyword related works differently. Of course I tried my keywords + words that weren't in my config file.
Screenshot of the new config file structure for keywords:
![Annotation 2019-10-12 154154](https://user-images.githubusercontent.com/20988865/66702387-7da48a00-ed07-11e9-8fc4-d12e0786f427.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [?] Breaking change (fix or feature that would cause existing functionality to change)
 Simple_inputs now works with lists but can still work with strings
Keyword is now a list and not a string anymore, so it gets loaded as one.

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [?] All new and existing tests passed.
It passed my tests and I'm pretty sure it won't cause any new problems.

But if there is anything that I should do before you are able to merge this, please tell me.

2019-10-12 13:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NaomiProject/Naomi?pullRequest=217) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NaomiProject/Naomi?pullRequest=217) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NaomiProject/Naomi?pullRequest=217) it.</sub>

2019-10-14 02:08 UTC, aaronchantrill commented
Hey @jeliebig I've been busy the last couple of days. I'm downloading and testing this right now.

2019-10-14 04:46 UTC, aaronchantrill requested changes
Most of the changes look good. There are a couple of small issues.

First, if I start with the old profile.yml, I'm getting an error on line 41 of naomi/brain.py that 'str' object has no attribute 'copy'. If keyword is being read in as a string, then it should be converted to a list and then saved back to profile. In other words, the first time I run Naomi after applying this patch, it should automatically convert my wakeword into a list.

Second, the comparison on line 272 of naomi/mic.py is checking to see if the lower case sentence from input is contained in each word. If you are running with passive listen turned off and naomi is only hearing the wake word, then that seems to work, but if you have passive listen turned on or Naomi is hearing noises as words in addition to the wakeword, then that doesn't work.

In other words, if keyword contains ['naomi','computer'] and transcribed contains ['naomi what time is it'] Naomi does not recognize that a wakeword has been spoken.

I'm also not sure I'm crazy about always having to check the results of simple input to see if it has returned a string or a list. I think it might be good to define a fourth optional parameter that tells it to return a list rather than a string, and if that is set, then split the input on comma's. Something like ", return_list=False"

Anyway, it's really close, other than those few issues.

Another possibility is to define a new "nicknames" field which would have a list of names that Naomi would also react to. That way Naomi could react differently to someone using a nickname rather than the "proper" keyword. But that's not a requirement.

2019-10-14 11:23 UTC, jeliebig commented
Okay I will see if I can fix this today. It's probably an issue with my list or string check, so I just need to check why it doesn't work as intented. 

I noticed the wakeword bahavior too, but thought it was intented like that. I'll compare my code to the base branch again and add the other behavior as well.

Sorry for the current issues.

2019-10-14 12:11 UTC, aaronchantrill commented
Thank you for working on this, I can tell that you've put some effort into it, and I appreciate you working with Codacy to get all of its complaints fixed. And great job with writing the pull request, it is clear and well written.

2019-10-14 18:22 UTC, jeliebig commented
Okay the keyword detection now works properly!

I'll look into simple_input again and check if I can add the return value you mentioned

2019-10-14 18:32 UTC, jeliebig commented
I added the parameter to simple_input and set it to True for keyword population, so everything should be fine now!

2019-10-14 20:05 UTC, merged

2019-10-14 20:06 UTC, aaronchantrill commented
Tested, looks good. Merged.