Typos: punctuation and grammar fixing
NaomiProject/Naomi pull request #426
Opened 2024-10-16 10:35 UTC by sank8-2

## Description

Fixed necessary typos and punctuations.

## Motivation and Context

This improves the Readability of the Documents and gives users a seamless experience.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-10-19 12:27 UTC, sank8-2 commented
@aaronchantrill Hi, is this being reviewed?

2024-10-20 01:07 UTC, sank8-2 commented
@aaronchantrill Meanwhile review this too

2024-10-20 01:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NaomiProject/Naomi?pullRequest=426) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NaomiProject/Naomi?pullRequest=426) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NaomiProject/Naomi?pullRequest=426) it.</sub>

2024-10-20 21:42 UTC, aaronchantrill requested changes
Thank you for contributing. Here are my notes on this pull request:

First, I prefer not to change the changelog retroactively. Even though your changes are technically correct and don't appear to change the meanings of any of the entries, I still think it's bad form to modify changelogs retroactively, especially if the original author is unable to verify that the updated language is still correct. In this case, though, it appears that almost all of these were created by me, so I can verify that most of these are correct.

On line 30 - I would leave the "y" in "you" lowercase because it is continuing the previous line. This may mean that the colon on the previous line is not correct, but I think it works either way.

On line 65, I think the correct correction would be to change the "in" to "if", not a comma.

On line 87 I would change "then" to "and then" rather than ", and".

I don't think it helps to add the comma on line 91.

Lines 124, 144, 148 were written by AustinC, so I will tag them to review.

Line 181 - I'm not sure adding the oxford comma helps anything, but it also doesn't hurt anything, so I'd be inclined to allow your change.

CODE_OF_CONDUCT.md
Again, this was not written by me, so I will request a review by the original author, AustinC.

CONTRIBUTING.md
Again, not written by me, but written by AustinC.

Line 5- technically, then period should appear within the quotes, but this was always an awkward feature of English. I would prefer to keep the period outside the quotes.

Line 11 - I'm not sure why you prefer "along with" to "along side". The rest of your changes look fine.

Line 15 - your changes look fine.

Line 19 - your change looks fine

Line 25 - I would argue that the "from" in "from front to back" doesn't add anything, but the rest of the changes look fine.

Line 31 - I don't think the period at the end is really necessary, but it doesn't hurt anything.

Line 33 - same with this comma - it doesn't really add anything.

Lines 37-39 - "We do" is definitely better than "Do". The periods at the ends of points two and three don't really add anything, but don't hurt anything either.

Lines 43-45 - Your changes look fine to me.

Line 48 - Both "labeling" and "labelling" are technically correct. One is US English and the other is UK English. Since this is an international project, I don't have a preference, but don't want people to continue correcting the spellings of UK vs US spellings, so I would prefer you not change this spelling.

Line 50 - your change looks correct to me.

Line 69 - I have no idea why you inserted a space here.

Line 73 - The additional comma is probably correct, but removing the "about" is not. Would be better to rewrite as "Once submitted, the community will discuss the idea with you to help flesh it out..."

Line 75 - I'm not sure about the preference between "which" and "that" here. I'm not sure the reader would be confused about which Github issue is being referred to, but I'm willing to accept it.

Line 79 - Okay, looks fine.

Line 81 - I'm not sure why you are adding the angle bracket here, but I assume it is to make it consistent with line 69.

Line 89 - Your changes look fine to me.

Line 93 - Your changes look fine to me.

README.md

Lines 55 and 59 - I don't see your changes really improving the documentation, but they don't hurt either.

Line 98 - The original Jasper2fork project does not capitalize the "F".

2024-10-21 03:31 UTC, sank8-2 commented
@aaronchantrill Thanks for a detailed review, I made the necessary changes mentioned by you, and hearing from you they all seem to be right.
Just have to wait for @AustinCasteel to review it further.
Thank you
Sanketh

2024-10-22 19:34 UTC, aaronchantrill approved these changes
With the changes this is now acceptable to me. Thank you for working on this @sank8-2

2024-10-23 00:46 UTC, sank8-2 commented
@aaronchantrill Thanks

2024-10-30 20:27 UTC, AustinCasteel commented on CHANGELOG.md
I do not agree with updating the changelog after the fact. But since Aaron can verify the changes to his lines and then changes to my lines are good so it is fine.

2024-10-30 20:27 UTC, AustinCasteel commented on CODE_OF_CONDUCT.md
These changes here are not needed.

2024-10-30 20:27 UTC, AustinCasteel commented on CONTRIBUTING.md
> +* Ensure code compatibility for every change. We No-Code Leaderboard
This seems likes a typo.

2024-10-30 20:28 UTC, AustinCasteel commented on README.md
changes look fine

2024-10-30 20:29 UTC, AustinCasteel requested changes
Barring a couple tweaks looks good.

2024-10-30 20:42 UTC, aaronchantrill commented on CONTRIBUTING.md
> +* Ensure code compatibility for every change. We No-Code Leaderboard
Wow, okay, I missed that one.

2024-12-15 23:10 UTC, aaronchantrill commented
Closing. While we do appreciate the effort, ultimately we need to focus more on the content of the pages than the grammar and spelling. We pretty much need to re-write the whole site this year, so I'm closing this and will feed future pages to an automated checker as they are updated.

2024-12-15 23:10 UTC, closed without merging